### ISSUE TITLE
Sửa lại tiến độ project

### ISSUE THREAD

**Issue by Huynh-Dat** [PMiGroup/2017_14BIT1_iGroup_Project#5]

**Comment by Huynh-Dat** [comment]
sửa lại tiến độ đồ án rồi úp lên đây Huy ơi

**Comment by ceeril** [comment]
Báo cáo tiến độ hiện tại của project



[project.zip](https://github.com/PMiGroup/2017_14BIT1_iGroup_Project/files/1159794/project.zip)
