### ISSUE TITLE
Tạo db cho câu hỏi và lấy câu hỏi về

### ISSUE THREAD

**Issue by Huynh-Dat** [PMiGroup/2017_14BIT1_iGroup_Project#6]

**Comment by tnguyen878** [comment]
DB cho câu hỏi:
[questionaire.zip](https://github.com/PMiGroup/2017_14BIT1_iGroup_Project/files/1159599/questionaire.zip)

**Comment by tnguyen878** [comment]
cái này phải thêm 1 cột correctAnswer nữa nghe Đạt. Nếu ko thì ko thể kiểm trả lời đúng hay sai. Admin cũng ó thể sửa câu trả lời khi edit câu hỏi nữa. Mấy câu trả lời a chỉ điền vô cho có data thôi. Ko đúng đâu.

[questionaire.zip](https://github.com/PMiGroup/2017_14BIT1_iGroup_Project/files/1159898/questionaire.zip)

**Comment by Huynh-Dat** [comment]
ok
